apiVersion: v1
kind: Service
metadata:
  name: basic-nginx-webserver
  labels:
    app: basic-nginx-webserver
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: basic-nginx-webserver